services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --worker-class aiohttp.GunicornWebWorker --bind 0.0.0.0:10000
